name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    uses: intisy/workflows/.github/workflows/test.yml@main
    with:
      gradle_test: build
    secrets:
      envPAT: ${{ secrets.PAT }}
